<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.7" />
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

</Project>
